source 'https://rubygems.org'

gem 'badgerbadgerbadger'
gem 'coveralls'
gem 'jekyll', '~> 3.3.1'
gem 'jekyll-feed', '~> 0.8.0'
gem 'rake', '~> 11.3.0'
gem 'rdiscount', '~>2.2.0.1'
gem 's3_website', '~> 2.16.0'
gem 'therubyracer', '~> 0.12.2'